//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRental.RentalItemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentalItem", Namespace="http://schemas.datacontract.org/2004/07/VRWebServiceLibrary.Model")]
    [System.SerializableAttribute()]
    public partial class RentalItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MovieIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentalItemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieId {
            get {
                return this.MovieIdField;
            }
            set {
                if ((this.MovieIdField.Equals(value) != true)) {
                    this.MovieIdField = value;
                    this.RaisePropertyChanged("MovieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalId {
            get {
                return this.RentalIdField;
            }
            set {
                if ((this.RentalIdField.Equals(value) != true)) {
                    this.RentalIdField = value;
                    this.RaisePropertyChanged("RentalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentalItemId {
            get {
                return this.RentalItemIdField;
            }
            set {
                if ((this.RentalItemIdField.Equals(value) != true)) {
                    this.RentalItemIdField = value;
                    this.RaisePropertyChanged("RentalItemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalItemService.IRentalItemService")]
    public interface IRentalItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/GetRentalItems", ReplyAction="http://tempuri.org/IRentalItemService/GetRentalItemsResponse")]
        System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem> GetRentalItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/GetRentalItems", ReplyAction="http://tempuri.org/IRentalItemService/GetRentalItemsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem>> GetRentalItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/GetRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/GetRentalItemResponse")]
        VideoRental.RentalItemService.RentalItem GetRentalItem(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/GetRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/GetRentalItemResponse")]
        System.Threading.Tasks.Task<VideoRental.RentalItemService.RentalItem> GetRentalItemAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/GetRentalItemByRentalId", ReplyAction="http://tempuri.org/IRentalItemService/GetRentalItemByRentalIdResponse")]
        System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem> GetRentalItemByRentalId(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/GetRentalItemByRentalId", ReplyAction="http://tempuri.org/IRentalItemService/GetRentalItemByRentalIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem>> GetRentalItemByRentalIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/PutRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/PutRentalItemResponse")]
        bool PutRentalItem(int Id, VideoRental.RentalItemService.RentalItem rentalItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/PutRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/PutRentalItemResponse")]
        System.Threading.Tasks.Task<bool> PutRentalItemAsync(int Id, VideoRental.RentalItemService.RentalItem rentalItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/PostRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/PostRentalItemResponse")]
        int PostRentalItem(VideoRental.RentalItemService.RentalItem rentalItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/PostRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/PostRentalItemResponse")]
        System.Threading.Tasks.Task<int> PostRentalItemAsync(VideoRental.RentalItemService.RentalItem rentalItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/DeleteRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/DeleteRentalItemResponse")]
        int DeleteRentalItem(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalItemService/DeleteRentalItem", ReplyAction="http://tempuri.org/IRentalItemService/DeleteRentalItemResponse")]
        System.Threading.Tasks.Task<int> DeleteRentalItemAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalItemServiceChannel : VideoRental.RentalItemService.IRentalItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalItemServiceClient : System.ServiceModel.ClientBase<VideoRental.RentalItemService.IRentalItemService>, VideoRental.RentalItemService.IRentalItemService {
        
        public RentalItemServiceClient() {
        }
        
        public RentalItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem> GetRentalItems() {
            return base.Channel.GetRentalItems();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem>> GetRentalItemsAsync() {
            return base.Channel.GetRentalItemsAsync();
        }
        
        public VideoRental.RentalItemService.RentalItem GetRentalItem(int Id) {
            return base.Channel.GetRentalItem(Id);
        }
        
        public System.Threading.Tasks.Task<VideoRental.RentalItemService.RentalItem> GetRentalItemAsync(int Id) {
            return base.Channel.GetRentalItemAsync(Id);
        }
        
        public System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem> GetRentalItemByRentalId(int Id) {
            return base.Channel.GetRentalItemByRentalId(Id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<VideoRental.RentalItemService.RentalItem>> GetRentalItemByRentalIdAsync(int Id) {
            return base.Channel.GetRentalItemByRentalIdAsync(Id);
        }
        
        public bool PutRentalItem(int Id, VideoRental.RentalItemService.RentalItem rentalItem) {
            return base.Channel.PutRentalItem(Id, rentalItem);
        }
        
        public System.Threading.Tasks.Task<bool> PutRentalItemAsync(int Id, VideoRental.RentalItemService.RentalItem rentalItem) {
            return base.Channel.PutRentalItemAsync(Id, rentalItem);
        }
        
        public int PostRentalItem(VideoRental.RentalItemService.RentalItem rentalItem) {
            return base.Channel.PostRentalItem(rentalItem);
        }
        
        public System.Threading.Tasks.Task<int> PostRentalItemAsync(VideoRental.RentalItemService.RentalItem rentalItem) {
            return base.Channel.PostRentalItemAsync(rentalItem);
        }
        
        public int DeleteRentalItem(int Id) {
            return base.Channel.DeleteRentalItem(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteRentalItemAsync(int Id) {
            return base.Channel.DeleteRentalItemAsync(Id);
        }
    }
}
